#Hugo configuration
title = "Test"
baseURL = "https:\/\/http:\/\/stage.tvpage.com\/jpchang"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758991"
subfolder = "\/jpchang"
firstpartycookies = true
cookiedomain = "tvpage.com"
